@host = http://localhost:8000/api/v1

# @name login
POST  {{host}}/login
Content-Type: application/json

{
    "email":"daniel-16@correo.com",
    "password": "danielD"
}
###

# @name signup
POST  {{host}}/signup
Content-Type: application/json

{
    "name":"Daniel",
    "lastName":"Diaz",
    "phoneNumber":"3300000000",
    "kind":"user",
    "email":"daniel-{{$randomInt 0 100}}@correo.com",
    "password": "danielD"

}
###

# @name GetUser
GET {{host}}/user
Authorization: Bearer {{login.response.body.token}}
###
